package pumpkin:plugin@0.1.0;

interface biomes {
  enum biome {
    badlands,
    bamboo-jungle,
    basalt-deltas,
    beach,
    birch-forest,
    cherry-grove,
    cold-ocean,
    crimson-forest,
    dark-forest,
    deep-cold-ocean,
    deep-dark,
    deep-frozen-ocean,
    deep-lukewarm-ocean,
    deep-ocean,
    desert,
    dripstone-caves,
    end-barrens,
    end-highlands,
    end-midlands,
    eroded-badlands,
    flower-forest,
    forest,
    frozen-ocean,
    frozen-peaks,
    frozen-river,
    grove,
    ice-spikes,
    jagged-peaks,
    jungle,
    lukewarm-ocean,
    lush-caves,
    mangrove-swamp,
    meadow,
    mushroom-fields,
    nether-wastes,
    ocean,
    old-growth-birch-forest,
    old-growth-pine-taiga,
    old-growth-spruce-taiga,
    pale-garden,
    plains,
    river,
    savanna,
    savanna-plateau,
    small-end-islands,
    snowy-beach,
    snowy-plains,
    snowy-slopes,
    snowy-taiga,
    soul-sand-valley,
    sparse-jungle,
    stony-peaks,
    stony-shore,
    sulfur-caves,
    sunflower-plains,
    swamp,
    taiga,
    the-end,
    the-void,
    warm-ocean,
    warped-forest,
    windswept-forest,
    windswept-gravelly-hills,
    windswept-hills,
    windswept-savanna,
    wooded-badlands,
  }
}
