package pumpkin:plugin@0.1.0;

interface damage-types {
  enum damage-type {
    arrow,
    bad-respawn-point,
    cactus,
    campfire,
    cramming,
    dragon-breath,
    drown,
    dry-out,
    ender-pearl,
    explosion,
    fall,
    falling-anvil,
    falling-block,
    falling-stalactite,
    fireball,
    fireworks,
    fly-into-wall,
    freeze,
    generic,
    generic-kill,
    hot-floor,
    in-fire,
    in-wall,
    indirect-magic,
    lava,
    lightning-bolt,
    mace-smash,
    magic,
    mob-attack,
    mob-attack-no-aggro,
    mob-projectile,
    on-fire,
    out-of-world,
    outside-border,
    player-attack,
    player-explosion,
    sonic-boom,
    spear,
    spit,
    stalagmite,
    starve,
    sting,
    sulfur-cube-hot,
    sweet-berry-bush,
    thorns,
    thrown,
    trident,
    unattributed-fireball,
    wind-charge,
    wither,
    wither-skull,
  }
}
