package pumpkin:plugin@0.1.0;

interface data-components {
  enum data-component {
    custom-data,
    max-stack-size,
    max-damage,
    damage,
    unbreakable,
    use-effects,
    custom-name,
    minimum-attack-charge,
    damage-type,
    item-name,
    item-model,
    lore,
    rarity,
    enchantments,
    can-place-on,
    can-break,
    attribute-modifiers,
    custom-model-data,
    tooltip-display,
    repair-cost,
    creative-slot-lock,
    enchantment-glint-override,
    intangible-projectile,
    food,
    consumable,
    use-remainder,
    use-cooldown,
    damage-resistant,
    tool,
    weapon,
    attack-range,
    enchantable,
    equippable,
    repairable,
    glider,
    tooltip-style,
    death-protection,
    blocks-attacks,
    piercing-weapon,
    kinetic-weapon,
    swing-animation,
    additional-trade-cost,
    stored-enchantments,
    dye,
    dyed-color,
    map-color,
    map-id,
    map-decorations,
    map-post-processing,
    charged-projectiles,
    bundle-contents,
    potion-contents,
    potion-duration-scale,
    suspicious-stew-effects,
    writable-book-content,
    written-book-content,
    trim,
    debug-stick-state,
    entity-data,
    bucket-entity-data,
    block-entity-data,
    instrument,
    provides-trim-material,
    ominous-bottle-amplifier,
    jukebox-playable,
    provides-banner-patterns,
    recipes,
    lodestone-tracker,
    firework-explosion,
    fireworks,
    profile,
    note-block-sound,
    banner-patterns,
    base-color,
    pot-decorations,
    container,
    block-state,
    bees,
    sulfur-cube-content,
    lock,
    container-loot,
    break-sound,
    villager-variant,
    wolf-variant,
    wolf-sound-variant,
    wolf-collar,
    fox-variant,
    salmon-size,
    parrot-variant,
    tropical-fish-pattern,
    tropical-fish-base-color,
    tropical-fish-pattern-color,
    mooshroom-variant,
    rabbit-variant,
    pig-variant,
    pig-sound-variant,
    cow-variant,
    cow-sound-variant,
    chicken-variant,
    chicken-sound-variant,
    zombie-nautilus-variant,
    frog-variant,
    horse-variant,
    painting-variant,
    llama-variant,
    axolotl-variant,
    cat-variant,
    cat-sound-variant,
    cat-collar,
    sheep-color,
    shulker-color,
  }
}
