package pumpkin:plugin@0.1.0;

interface entity-statuses {
  enum entity-status {
    armadillo-peek,
    armorstand-wobble,
    body-break,
    cancel-shake-wetness,
    chest-break,
    death,
    dolphin-looking-for-treasure,
    drown-particles,
    eat-grass,
    end-ram,
    feet-break,
    fireworks-explode,
    fishing-rod-reel-in,
    fox-eat,
    full-debug-info,
    guardian-attack-sound,
    head-break,
    honey-jump,
    honey-slide,
    in-love-hearts,
    jump,
    kinetic-hit,
    legs-break,
    love-hearts,
    mainhand-break,
    offer-flower,
    offhand-break,
    permission-level-admins,
    permission-level-all,
    permission-level-gamemasters,
    permission-level-moderators,
    permission-level-owners,
    poof,
    protected-from-death,
    ravager-roared,
    ravager-stunned,
    reduced-debug-info,
    saddle-break,
    shake,
    shake-wetness,
    silverfish-merge-anim,
    sniffer-digging-sound,
    sonic-charge,
    squid-anim-synch,
    start-attacking,
    start-ram,
    stop-attacking,
    stop-offer-flower,
    swap-hands,
    taming-failed,
    taming-succeeded,
    teleport,
    tendrils-shiver,
    tnt-prime,
    trusting-failed,
    trusting-succeeded,
    use-item-complete,
    villager-angry,
    villager-happy,
    villager-sweat,
    witch-hat-magic,
    zombie-converting,
  }
}
