package pumpkin:plugin@0.1.0;

interface game-events {
  enum game-event {
    block-activate,
    block-attach,
    block-change,
    block-close,
    block-deactivate,
    block-destroy,
    block-detach,
    block-open,
    block-place,
    bounce,
    container-close,
    container-open,
    drink,
    eat,
    elytra-glide,
    entity-damage,
    entity-die,
    entity-dismount,
    entity-interact,
    entity-mount,
    entity-place,
    entity-action,
    equip,
    explode,
    flap,
    fluid-pickup,
    fluid-place,
    hit-ground,
    instrument-play,
    item-interact-finish,
    item-interact-start,
    jukebox-play,
    jukebox-stop-play,
    lightning-strike,
    note-block-play,
    prime-fuse,
    projectile-land,
    projectile-shoot,
    sculk-sensor-tendrils-clicking,
    shear,
    shriek,
    splash,
    step,
    swim,
    teleport,
    unequip,
    resonate-1,
    resonate-2,
    resonate-3,
    resonate-4,
    resonate-5,
    resonate-6,
    resonate-7,
    resonate-8,
    resonate-9,
    resonate-10,
    resonate-11,
    resonate-12,
    resonate-13,
    resonate-14,
    resonate-15,
  }
}
