package pumpkin:plugin@0.1.0;

interface particles {
  enum particle {
    angry-villager,
    block,
    block-marker,
    bubble,
    sulfur-bubbles,
    noxious-gas,
    noxious-gas-cloud,
    geyser,
    geyser-base,
    geyser-poof,
    geyser-plume,
    cloud,
    copper-fire-flame,
    crit,
    damage-indicator,
    dragon-breath,
    dripping-lava,
    falling-lava,
    landing-lava,
    dripping-water,
    falling-water,
    dust,
    dust-color-transition,
    effect,
    elder-guardian,
    enchanted-hit,
    enchant,
    end-rod,
    entity-effect,
    explosion-emitter,
    explosion,
    gust,
    small-gust,
    gust-emitter-large,
    gust-emitter-small,
    sonic-boom,
    falling-dust,
    firework,
    fishing,
    flame,
    infested,
    cherry-leaves,
    pale-oak-leaves,
    tinted-leaves,
    sculk-soul,
    sculk-charge,
    sculk-charge-pop,
    soul-fire-flame,
    soul,
    flash,
    happy-villager,
    composter,
    heart,
    instant-effect,
    item,
    vibration,
    trail,
    pause-mob-growth,
    reset-mob-growth,
    item-slime,
    item-cobweb,
    item-snowball,
    large-smoke,
    lava,
    mycelium,
    note,
    poof,
    portal,
    rain,
    smoke,
    white-smoke,
    sneeze,
    spit,
    squid-ink,
    sweep-attack,
    totem-of-undying,
    underwater,
    splash,
    witch,
    bubble-pop,
    current-down,
    bubble-column-up,
    nautilus,
    dolphin,
    campfire-cosy-smoke,
    campfire-signal-smoke,
    dripping-honey,
    falling-honey,
    landing-honey,
    falling-nectar,
    falling-spore-blossom,
    ash,
    crimson-spore,
    warped-spore,
    spore-blossom-air,
    dripping-obsidian-tear,
    falling-obsidian-tear,
    landing-obsidian-tear,
    reverse-portal,
    white-ash,
    small-flame,
    snowflake,
    dripping-dripstone-lava,
    falling-dripstone-lava,
    dripping-dripstone-water,
    falling-dripstone-water,
    glow-squid-ink,
    glow,
    wax-on,
    wax-off,
    electric-spark,
    scrape,
    shriek,
    egg-crack,
    dust-plume,
    trial-spawner-detection,
    trial-spawner-detection-ominous,
    vault-connection,
    dust-pillar,
    ominous-spawning,
    raid-omen,
    trial-omen,
    block-crumble,
    firefly,
    sulfur-cube-goo,
  }
}
