package pumpkin:plugin@0.1.0;

interface potions {
  enum potion-type {
    water,
    mundane,
    thick,
    awkward,
    night-vision,
    long-night-vision,
    invisibility,
    long-invisibility,
    leaping,
    long-leaping,
    strong-leaping,
    fire-resistance,
    long-fire-resistance,
    swiftness,
    long-swiftness,
    strong-swiftness,
    slowness,
    long-slowness,
    strong-slowness,
    turtle-master,
    long-turtle-master,
    strong-turtle-master,
    water-breathing,
    long-water-breathing,
    healing,
    strong-healing,
    harming,
    strong-harming,
    poison,
    long-poison,
    strong-poison,
    regeneration,
    long-regeneration,
    strong-regeneration,
    strength,
    long-strength,
    strong-strength,
    weakness,
    long-weakness,
    luck,
    slow-falling,
    long-slow-falling,
    wind-charged,
    weaving,
    oozing,
    infested,
  }
}
