package pumpkin:plugin@0.1.0;

interface sounds {
  enum sound-category {
    master,
    music,
    records,
    weather,
    blocks,
    hostile,
    neutral,
    players,
    ambient,
    voice,
    ui,
  }
  enum sound {
    entity-allay-ambient-with-item,
    entity-allay-ambient-without-item,
    entity-allay-death,
    entity-allay-hurt,
    entity-allay-item-given,
    entity-allay-item-taken,
    entity-allay-item-thrown,
    ambient-cave,
    ambient-basalt-deltas-additions,
    ambient-basalt-deltas-loop,
    ambient-basalt-deltas-mood,
    ambient-crimson-forest-additions,
    ambient-crimson-forest-loop,
    ambient-crimson-forest-mood,
    ambient-nether-wastes-additions,
    ambient-nether-wastes-loop,
    ambient-nether-wastes-mood,
    ambient-soul-sand-valley-additions,
    ambient-soul-sand-valley-loop,
    ambient-soul-sand-valley-mood,
    ambient-warped-forest-additions,
    ambient-warped-forest-loop,
    ambient-warped-forest-mood,
    ambient-underwater-enter,
    ambient-underwater-exit,
    ambient-underwater-loop,
    ambient-underwater-loop-additions,
    ambient-underwater-loop-additions-rare,
    ambient-underwater-loop-additions-ultra-rare,
    block-amethyst-block-break,
    block-amethyst-block-chime,
    block-amethyst-block-fall,
    block-amethyst-block-hit,
    block-amethyst-block-place,
    block-amethyst-block-resonate,
    block-amethyst-block-step,
    block-amethyst-cluster-break,
    block-amethyst-cluster-fall,
    block-amethyst-cluster-hit,
    block-amethyst-cluster-place,
    block-amethyst-cluster-step,
    block-ancient-debris-break,
    block-ancient-debris-step,
    block-ancient-debris-place,
    block-ancient-debris-hit,
    block-ancient-debris-fall,
    block-anvil-break,
    block-anvil-destroy,
    block-anvil-fall,
    block-anvil-hit,
    block-anvil-land,
    block-anvil-place,
    block-anvil-step,
    block-anvil-use,
    entity-armadillo-eat,
    entity-armadillo-hurt,
    entity-armadillo-hurt-reduced,
    entity-armadillo-ambient,
    entity-armadillo-step,
    entity-armadillo-death,
    entity-armadillo-roll,
    entity-armadillo-land,
    entity-armadillo-scute-drop,
    entity-armadillo-unroll-finish,
    entity-armadillo-peek,
    entity-armadillo-unroll-start,
    entity-armadillo-brush,
    item-armor-equip-chain,
    item-armor-equip-diamond,
    item-armor-equip-elytra,
    item-armor-equip-generic,
    item-armor-equip-gold,
    item-armor-equip-iron,
    item-armor-equip-leather,
    item-armor-equip-copper,
    item-armor-equip-netherite,
    item-armor-equip-turtle,
    item-armor-equip-wolf,
    item-armor-unequip-wolf,
    item-armor-equip-nautilus,
    item-armor-unequip-nautilus,
    entity-armor-stand-break,
    entity-armor-stand-fall,
    entity-armor-stand-hit,
    entity-armor-stand-place,
    entity-arrow-hit,
    entity-arrow-hit-player,
    entity-arrow-shoot,
    item-axe-strip,
    item-axe-scrape,
    item-axe-wax-off,
    entity-axolotl-attack,
    entity-axolotl-death,
    entity-axolotl-hurt,
    entity-axolotl-idle-air,
    entity-axolotl-idle-water,
    entity-axolotl-splash,
    entity-axolotl-swim,
    block-azalea-break,
    block-azalea-fall,
    block-azalea-hit,
    block-azalea-place,
    block-azalea-step,
    block-azalea-leaves-break,
    block-azalea-leaves-fall,
    block-azalea-leaves-hit,
    block-azalea-leaves-place,
    block-azalea-leaves-step,
    entity-baby-nautilus-ambient,
    entity-baby-nautilus-ambient-land,
    entity-baby-nautilus-death,
    entity-baby-nautilus-death-land,
    entity-baby-nautilus-eat,
    entity-baby-nautilus-hurt,
    entity-baby-nautilus-hurt-land,
    entity-nautilus-riding,
    entity-baby-nautilus-swim,
    block-bamboo-break,
    block-bamboo-fall,
    block-bamboo-hit,
    block-bamboo-place,
    block-bamboo-step,
    block-bamboo-sapling-break,
    block-bamboo-sapling-hit,
    block-bamboo-sapling-place,
    block-bamboo-wood-break,
    block-bamboo-wood-fall,
    block-bamboo-wood-hit,
    block-bamboo-wood-place,
    block-bamboo-wood-step,
    block-bamboo-wood-door-close,
    block-bamboo-wood-door-open,
    block-bamboo-wood-trapdoor-close,
    block-bamboo-wood-trapdoor-open,
    block-bamboo-wood-button-click-off,
    block-bamboo-wood-button-click-on,
    block-bamboo-wood-pressure-plate-click-off,
    block-bamboo-wood-pressure-plate-click-on,
    block-bamboo-wood-fence-gate-close,
    block-bamboo-wood-fence-gate-open,
    block-barrel-close,
    block-barrel-open,
    block-basalt-break,
    block-basalt-step,
    block-basalt-place,
    block-basalt-hit,
    block-basalt-fall,
    entity-bat-ambient,
    entity-bat-death,
    entity-bat-hurt,
    entity-bat-loop,
    entity-bat-takeoff,
    block-beacon-activate,
    block-beacon-ambient,
    block-beacon-deactivate,
    block-beacon-power-select,
    entity-bee-death,
    entity-bee-hurt,
    entity-bee-loop-aggressive,
    entity-bee-loop,
    entity-bee-sting,
    entity-bee-pollinate,
    block-beehive-drip,
    block-beehive-enter,
    block-beehive-exit,
    block-beehive-shear,
    block-beehive-work,
    block-bell-use,
    block-bell-resonate,
    block-big-dripleaf-break,
    block-big-dripleaf-fall,
    block-big-dripleaf-hit,
    block-big-dripleaf-place,
    block-big-dripleaf-step,
    entity-blaze-ambient,
    entity-blaze-burn,
    entity-blaze-death,
    entity-blaze-hurt,
    entity-blaze-shoot,
    entity-boat-paddle-land,
    entity-boat-paddle-water,
    entity-bogged-ambient,
    entity-bogged-death,
    entity-bogged-hurt,
    entity-bogged-shear,
    entity-bogged-step,
    block-bone-block-break,
    block-bone-block-fall,
    block-bone-block-hit,
    block-bone-block-place,
    block-bone-block-step,
    item-bone-meal-use,
    item-book-page-turn,
    item-book-put,
    block-blastfurnace-fire-crackle,
    item-bottle-empty,
    item-bottle-fill,
    item-bottle-fill-dragonbreath,
    entity-breeze-charge,
    entity-breeze-deflect,
    entity-breeze-inhale,
    entity-breeze-idle-ground,
    entity-breeze-idle-air,
    entity-breeze-shoot,
    entity-breeze-jump,
    entity-breeze-land,
    entity-breeze-slide,
    entity-breeze-death,
    entity-breeze-hurt,
    entity-breeze-whirl,
    entity-breeze-wind-burst,
    block-brewing-stand-brew,
    item-brush-brushing-generic,
    item-brush-brushing-sand,
    item-brush-brushing-gravel,
    item-brush-brushing-sand-complete,
    item-brush-brushing-gravel-complete,
    block-bubble-column-bubble-pop,
    block-bubble-column-upwards-ambient,
    block-bubble-column-upwards-inside,
    block-bubble-column-whirlpool-ambient,
    block-bubble-column-whirlpool-inside,
    ui-hud-bubble-pop,
    item-bucket-empty,
    item-bucket-empty-axolotl,
    item-bucket-empty-fish,
    item-bucket-empty-lava,
    item-bucket-empty-powder-snow,
    item-bucket-empty-sulfur-cube,
    item-bucket-empty-tadpole,
    item-bucket-fill,
    item-bucket-fill-axolotl,
    item-bucket-fill-fish,
    item-bucket-fill-lava,
    item-bucket-fill-powder-snow,
    item-bucket-fill-sulfur-cube,
    item-bucket-fill-tadpole,
    item-bundle-drop-contents,
    item-bundle-insert,
    item-bundle-insert-fail,
    item-bundle-remove-one,
    block-cactus-flower-break,
    block-cactus-flower-place,
    block-cake-add-candle,
    block-calcite-break,
    block-calcite-step,
    block-calcite-place,
    block-calcite-hit,
    block-calcite-fall,
    entity-camel-husk-ambient,
    entity-camel-husk-dash,
    entity-camel-husk-dash-ready,
    entity-camel-husk-death,
    entity-camel-husk-eat,
    entity-camel-husk-hurt,
    entity-camel-husk-saddle,
    entity-camel-husk-sit,
    entity-camel-husk-stand,
    entity-camel-husk-step,
    entity-camel-husk-step-sand,
    entity-camel-ambient,
    entity-camel-dash,
    entity-camel-dash-ready,
    entity-camel-death,
    entity-camel-eat,
    entity-camel-hurt,
    entity-camel-saddle,
    entity-camel-sit,
    entity-camel-stand,
    entity-camel-step,
    entity-camel-step-sand,
    block-campfire-crackle,
    block-candle-ambient,
    block-candle-break,
    block-candle-extinguish,
    block-candle-fall,
    block-candle-hit,
    block-candle-place,
    block-candle-step,
    entity-baby-cat-ambient,
    entity-baby-cat-stray-ambient,
    entity-baby-cat-death,
    entity-baby-cat-eat,
    entity-baby-cat-hiss,
    entity-baby-cat-beg-for-food,
    entity-baby-cat-hurt,
    entity-baby-cat-purr,
    entity-baby-cat-purreow,
    entity-cat-ambient,
    entity-cat-stray-ambient,
    entity-cat-hiss,
    entity-cat-hurt,
    entity-cat-death,
    entity-cat-eat,
    entity-cat-beg-for-food,
    entity-cat-purr,
    entity-cat-purreow,
    entity-cat-royal-ambient,
    entity-cat-royal-stray-ambient,
    entity-cat-royal-hiss,
    entity-cat-royal-hurt,
    entity-cat-royal-death,
    entity-cat-royal-eat,
    entity-cat-royal-beg-for-food,
    entity-cat-royal-purr,
    entity-cat-royal-purreow,
    block-cave-vines-break,
    block-cave-vines-fall,
    block-cave-vines-hit,
    block-cave-vines-place,
    block-cave-vines-step,
    block-cave-vines-pick-berries,
    block-chain-break,
    block-chain-fall,
    block-chain-hit,
    block-chain-place,
    block-chain-step,
    block-cherry-wood-break,
    block-cherry-wood-fall,
    block-cherry-wood-hit,
    block-cherry-wood-place,
    block-cherry-wood-step,
    block-cherry-sapling-break,
    block-cherry-sapling-fall,
    block-cherry-sapling-hit,
    block-cherry-sapling-place,
    block-cherry-sapling-step,
    block-cherry-leaves-break,
    block-cherry-leaves-fall,
    block-cherry-leaves-hit,
    block-cherry-leaves-place,
    block-cherry-leaves-step,
    block-cherry-wood-hanging-sign-step,
    block-cherry-wood-hanging-sign-break,
    block-cherry-wood-hanging-sign-fall,
    block-cherry-wood-hanging-sign-hit,
    block-cherry-wood-hanging-sign-place,
    block-cherry-wood-door-close,
    block-cherry-wood-door-open,
    block-cherry-wood-trapdoor-close,
    block-cherry-wood-trapdoor-open,
    block-cherry-wood-button-click-off,
    block-cherry-wood-button-click-on,
    block-cherry-wood-pressure-plate-click-off,
    block-cherry-wood-pressure-plate-click-on,
    block-cherry-wood-fence-gate-close,
    block-cherry-wood-fence-gate-open,
    block-chest-close,
    block-chest-locked,
    block-chest-open,
    entity-baby-chicken-ambient,
    entity-baby-chicken-death,
    entity-chicken-egg,
    entity-baby-chicken-hurt,
    entity-chicken-step,
    entity-baby-chicken-step,
    entity-chicken-ambient,
    entity-chicken-hurt,
    entity-chicken-death,
    entity-chicken-picky-ambient,
    entity-chicken-picky-hurt,
    entity-chicken-picky-death,
    block-chiseled-bookshelf-break,
    block-chiseled-bookshelf-fall,
    block-chiseled-bookshelf-hit,
    block-chiseled-bookshelf-insert,
    block-chiseled-bookshelf-insert-enchanted,
    block-chiseled-bookshelf-step,
    block-chiseled-bookshelf-pickup,
    block-chiseled-bookshelf-pickup-enchanted,
    block-chiseled-bookshelf-place,
    block-chorus-flower-death,
    block-chorus-flower-grow,
    item-chorus-fruit-teleport,
    block-cobweb-break,
    block-cobweb-step,
    block-cobweb-place,
    block-cobweb-hit,
    block-cobweb-fall,
    entity-cod-ambient,
    entity-cod-death,
    entity-cod-flop,
    entity-cod-hurt,
    block-comparator-click,
    block-composter-empty,
    block-composter-fill,
    block-composter-fill-success,
    block-composter-ready,
    block-conduit-activate,
    block-conduit-ambient,
    block-conduit-ambient-short,
    block-conduit-attack-target,
    block-conduit-deactivate,
    block-copper-bulb-break,
    block-copper-bulb-step,
    block-copper-bulb-place,
    block-copper-bulb-hit,
    block-copper-bulb-fall,
    block-copper-bulb-turn-on,
    block-copper-bulb-turn-off,
    block-copper-break,
    block-copper-step,
    block-copper-place,
    block-copper-hit,
    block-copper-fall,
    block-copper-chest-close,
    block-copper-chest-open,
    block-copper-chest-weathered-close,
    block-copper-chest-weathered-open,
    block-copper-chest-oxidized-close,
    block-copper-chest-oxidized-open,
    block-copper-door-close,
    block-copper-door-open,
    entity-copper-golem-step,
    entity-copper-golem-hurt,
    entity-copper-golem-death,
    entity-copper-golem-weathered-step,
    entity-copper-golem-weathered-hurt,
    entity-copper-golem-weathered-death,
    entity-copper-golem-oxidized-step,
    entity-copper-golem-oxidized-hurt,
    entity-copper-golem-oxidized-death,
    entity-copper-golem-spin,
    entity-copper-golem-weathered-spin,
    entity-copper-golem-oxidized-spin,
    entity-copper-golem-no-item-get,
    entity-copper-golem-no-item-no-get,
    entity-copper-golem-item-drop,
    entity-copper-golem-item-no-drop,
    entity-copper-golem-become-statue,
    block-copper-golem-statue-break,
    block-copper-golem-statue-place,
    block-copper-golem-statue-hit,
    block-copper-golem-statue-step,
    block-copper-golem-statue-fall,
    entity-copper-golem-spawn,
    entity-copper-golem-shear,
    block-copper-grate-break,
    block-copper-grate-step,
    block-copper-grate-place,
    block-copper-grate-hit,
    block-copper-grate-fall,
    block-copper-trapdoor-close,
    block-copper-trapdoor-open,
    block-coral-block-break,
    block-coral-block-fall,
    block-coral-block-hit,
    block-coral-block-place,
    block-coral-block-step,
    entity-cow-milk,
    entity-cow-ambient,
    entity-cow-hurt,
    entity-cow-death,
    entity-cow-step,
    entity-cow-moody-ambient,
    entity-cow-moody-hurt,
    entity-cow-moody-death,
    entity-cow-moody-step,
    block-crafter-craft,
    block-crafter-fail,
    entity-creaking-ambient,
    entity-creaking-activate,
    entity-creaking-deactivate,
    entity-creaking-attack,
    entity-creaking-death,
    entity-creaking-step,
    entity-creaking-freeze,
    entity-creaking-unfreeze,
    entity-creaking-spawn,
    entity-creaking-sway,
    entity-creaking-twitch,
    block-creaking-heart-break,
    block-creaking-heart-fall,
    block-creaking-heart-hit,
    block-creaking-heart-hurt,
    block-creaking-heart-place,
    block-creaking-heart-step,
    block-creaking-heart-idle,
    block-creaking-heart-spawn,
    entity-creeper-death,
    entity-creeper-hurt,
    entity-creeper-primed,
    block-crop-break,
    item-crop-plant,
    item-crossbow-hit,
    item-crossbow-loading-end,
    item-crossbow-loading-middle,
    item-crossbow-loading-start,
    item-crossbow-quick-charge-1,
    item-crossbow-quick-charge-2,
    item-crossbow-quick-charge-3,
    item-crossbow-shoot,
    block-deadbush-idle,
    block-decorated-pot-break,
    block-decorated-pot-fall,
    block-decorated-pot-hit,
    block-decorated-pot-insert,
    block-decorated-pot-insert-fail,
    block-decorated-pot-step,
    block-decorated-pot-place,
    block-decorated-pot-shatter,
    block-deepslate-bricks-break,
    block-deepslate-bricks-fall,
    block-deepslate-bricks-hit,
    block-deepslate-bricks-place,
    block-deepslate-bricks-step,
    block-deepslate-break,
    block-deepslate-fall,
    block-deepslate-hit,
    block-deepslate-place,
    block-deepslate-step,
    block-deepslate-tiles-break,
    block-deepslate-tiles-fall,
    block-deepslate-tiles-hit,
    block-deepslate-tiles-place,
    block-deepslate-tiles-step,
    block-dispenser-dispense,
    block-dispenser-fail,
    block-dispenser-launch,
    entity-dolphin-ambient,
    entity-dolphin-ambient-water,
    entity-dolphin-attack,
    entity-dolphin-death,
    entity-dolphin-eat,
    entity-dolphin-hurt,
    entity-dolphin-jump,
    entity-dolphin-play,
    entity-dolphin-splash,
    entity-dolphin-swim,
    entity-donkey-ambient,
    entity-donkey-angry,
    entity-donkey-chest,
    entity-donkey-death,
    entity-donkey-eat,
    entity-donkey-hurt,
    entity-donkey-jump,
    block-dried-ghast-break,
    block-dried-ghast-step,
    block-dried-ghast-fall,
    block-dried-ghast-ambient,
    block-dried-ghast-ambient-water,
    block-dried-ghast-place,
    block-dried-ghast-place-in-water,
    block-dried-ghast-transition,
    block-dripstone-block-break,
    block-dripstone-block-step,
    block-dripstone-block-place,
    block-dripstone-block-hit,
    block-dripstone-block-fall,
    block-dry-grass-ambient,
    block-pointed-dripstone-break,
    block-pointed-dripstone-step,
    block-pointed-dripstone-place,
    block-pointed-dripstone-hit,
    block-pointed-dripstone-fall,
    block-pointed-dripstone-land,
    block-pointed-dripstone-drip-lava,
    block-pointed-dripstone-drip-water,
    block-pointed-dripstone-drip-lava-into-cauldron,
    block-pointed-dripstone-drip-water-into-cauldron,
    block-big-dripleaf-tilt-down,
    block-big-dripleaf-tilt-up,
    entity-drowned-ambient,
    entity-drowned-ambient-water,
    entity-drowned-death,
    entity-drowned-death-water,
    entity-drowned-hurt,
    entity-drowned-hurt-water,
    entity-drowned-shoot,
    entity-drowned-step,
    entity-drowned-swim,
    item-dye-use,
    entity-egg-throw,
    entity-elder-guardian-ambient,
    entity-elder-guardian-ambient-land,
    entity-elder-guardian-curse,
    entity-elder-guardian-death,
    entity-elder-guardian-death-land,
    entity-elder-guardian-flop,
    entity-elder-guardian-hurt,
    entity-elder-guardian-hurt-land,
    item-elytra-flying,
    block-enchantment-table-use,
    block-ender-chest-close,
    block-ender-chest-open,
    entity-ender-dragon-ambient,
    entity-ender-dragon-death,
    entity-dragon-fireball-explode,
    entity-ender-dragon-flap,
    entity-ender-dragon-growl,
    entity-ender-dragon-hurt,
    entity-ender-dragon-shoot,
    entity-ender-eye-death,
    entity-ender-eye-launch,
    entity-enderman-ambient,
    entity-enderman-death,
    entity-enderman-hurt,
    entity-enderman-scream,
    entity-enderman-stare,
    entity-enderman-teleport,
    entity-endermite-ambient,
    entity-endermite-death,
    entity-endermite-hurt,
    entity-endermite-step,
    entity-ender-pearl-throw,
    block-end-gateway-spawn,
    block-end-portal-frame-fill,
    block-end-portal-spawn,
    entity-evoker-ambient,
    entity-evoker-cast-spell,
    entity-evoker-celebrate,
    entity-evoker-death,
    entity-evoker-fangs-attack,
    entity-evoker-hurt,
    entity-evoker-prepare-attack,
    entity-evoker-prepare-summon,
    entity-evoker-prepare-wololo,
    entity-experience-bottle-throw,
    entity-experience-orb-pickup,
    block-eyeblossom-open-long,
    block-eyeblossom-open,
    block-eyeblossom-close-long,
    block-eyeblossom-close,
    block-eyeblossom-idle,
    block-fence-gate-close,
    block-fence-gate-open,
    item-firecharge-use,
    block-firefly-bush-idle,
    entity-firework-rocket-blast,
    entity-firework-rocket-blast-far,
    entity-firework-rocket-large-blast,
    entity-firework-rocket-large-blast-far,
    entity-firework-rocket-launch,
    entity-firework-rocket-shoot,
    entity-firework-rocket-twinkle,
    entity-firework-rocket-twinkle-far,
    block-fire-ambient,
    block-fire-extinguish,
    entity-fish-swim,
    entity-fishing-bobber-retrieve,
    entity-fishing-bobber-splash,
    entity-fishing-bobber-throw,
    item-flintandsteel-use,
    block-flowering-azalea-break,
    block-flowering-azalea-fall,
    block-flowering-azalea-hit,
    block-flowering-azalea-place,
    block-flowering-azalea-step,
    entity-fox-aggro,
    entity-fox-ambient,
    entity-fox-bite,
    entity-fox-death,
    entity-fox-eat,
    entity-fox-hurt,
    entity-fox-screech,
    entity-fox-sleep,
    entity-fox-sniff,
    entity-fox-spit,
    entity-fox-teleport,
    block-suspicious-sand-break,
    block-suspicious-sand-step,
    block-suspicious-sand-place,
    block-suspicious-sand-hit,
    block-suspicious-sand-fall,
    block-suspicious-gravel-break,
    block-suspicious-gravel-step,
    block-suspicious-gravel-place,
    block-suspicious-gravel-hit,
    block-suspicious-gravel-fall,
    block-froglight-break,
    block-froglight-fall,
    block-froglight-hit,
    block-froglight-place,
    block-froglight-step,
    block-frogspawn-step,
    block-frogspawn-break,
    block-frogspawn-fall,
    block-frogspawn-hatch,
    block-frogspawn-hit,
    block-frogspawn-place,
    entity-frog-ambient,
    entity-frog-death,
    entity-frog-eat,
    entity-frog-hurt,
    entity-frog-lay-spawn,
    entity-frog-long-jump,
    entity-frog-step,
    entity-frog-tongue,
    block-roots-break,
    block-roots-step,
    block-roots-place,
    block-roots-hit,
    block-roots-fall,
    block-furnace-fire-crackle,
    entity-generic-big-fall,
    entity-generic-burn,
    entity-generic-death,
    entity-generic-drink,
    entity-generic-eat,
    entity-generic-explode,
    entity-generic-extinguish-fire,
    entity-generic-hurt,
    entity-generic-small-fall,
    entity-generic-splash,
    entity-generic-swim,
    entity-ghast-ambient,
    entity-ghast-death,
    entity-ghast-hurt,
    entity-ghast-scream,
    entity-ghast-shoot,
    entity-ghast-warn,
    entity-ghastling-ambient,
    entity-ghastling-death,
    entity-ghastling-hurt,
    entity-ghastling-spawn,
    block-gilded-blackstone-break,
    block-gilded-blackstone-fall,
    block-gilded-blackstone-hit,
    block-gilded-blackstone-place,
    block-gilded-blackstone-step,
    block-glass-break,
    block-glass-fall,
    block-glass-hit,
    block-glass-place,
    block-glass-step,
    item-glow-ink-sac-use,
    entity-glow-item-frame-add-item,
    entity-glow-item-frame-break,
    entity-glow-item-frame-place,
    entity-glow-item-frame-remove-item,
    entity-glow-item-frame-rotate-item,
    entity-glow-squid-ambient,
    entity-glow-squid-death,
    entity-glow-squid-hurt,
    entity-glow-squid-squirt,
    entity-goat-ambient,
    entity-goat-death,
    entity-goat-eat,
    entity-goat-hurt,
    entity-goat-long-jump,
    entity-goat-milk,
    entity-goat-prepare-ram,
    entity-goat-ram-impact,
    entity-goat-horn-break,
    entity-goat-screaming-ambient,
    entity-goat-screaming-death,
    entity-goat-screaming-eat,
    entity-goat-screaming-hurt,
    entity-goat-screaming-long-jump,
    entity-goat-screaming-milk,
    entity-goat-screaming-prepare-ram,
    entity-goat-screaming-ram-impact,
    entity-goat-step,
    item-golden-dandelion-use,
    item-golden-dandelion-unuse,
    block-grass-break,
    block-grass-fall,
    block-grass-hit,
    block-grass-place,
    block-grass-step,
    block-gravel-break,
    block-gravel-fall,
    block-gravel-hit,
    block-gravel-place,
    block-gravel-step,
    block-grindstone-use,
    block-growing-plant-crop,
    entity-guardian-ambient,
    entity-guardian-ambient-land,
    entity-guardian-attack,
    entity-guardian-death,
    entity-guardian-death-land,
    entity-guardian-flop,
    entity-guardian-hurt,
    entity-guardian-hurt-land,
    block-hanging-roots-break,
    block-hanging-roots-fall,
    block-hanging-roots-hit,
    block-hanging-roots-place,
    block-hanging-roots-step,
    block-hanging-sign-step,
    block-hanging-sign-break,
    block-hanging-sign-fall,
    block-hanging-sign-hit,
    block-hanging-sign-place,
    entity-happy-ghast-ambient,
    entity-happy-ghast-death,
    entity-happy-ghast-hurt,
    entity-happy-ghast-riding,
    block-heavy-core-break,
    block-heavy-core-fall,
    block-heavy-core-hit,
    block-heavy-core-place,
    block-heavy-core-step,
    block-nether-wood-hanging-sign-step,
    block-nether-wood-hanging-sign-break,
    block-nether-wood-hanging-sign-fall,
    block-nether-wood-hanging-sign-hit,
    block-nether-wood-hanging-sign-place,
    block-bamboo-wood-hanging-sign-step,
    block-bamboo-wood-hanging-sign-break,
    block-bamboo-wood-hanging-sign-fall,
    block-bamboo-wood-hanging-sign-hit,
    block-bamboo-wood-hanging-sign-place,
    block-trial-spawner-break,
    block-trial-spawner-step,
    block-trial-spawner-place,
    block-trial-spawner-hit,
    block-trial-spawner-fall,
    block-trial-spawner-spawn-mob,
    block-trial-spawner-about-to-spawn-item,
    block-trial-spawner-spawn-item,
    block-trial-spawner-spawn-item-begin,
    block-trial-spawner-detect-player,
    block-trial-spawner-ominous-activate,
    block-trial-spawner-ambient,
    block-trial-spawner-ambient-ominous,
    block-trial-spawner-open-shutter,
    block-trial-spawner-close-shutter,
    block-trial-spawner-eject-item,
    entity-happy-ghast-equip,
    entity-happy-ghast-unequip,
    entity-happy-ghast-harness-goggles-up,
    entity-happy-ghast-harness-goggles-down,
    item-hoe-till,
    entity-hoglin-ambient,
    entity-hoglin-angry,
    entity-hoglin-attack,
    entity-hoglin-converted-to-zombified,
    entity-hoglin-death,
    entity-hoglin-hurt,
    entity-hoglin-retreat,
    entity-hoglin-step,
    block-honey-block-break,
    block-honey-block-fall,
    block-honey-block-hit,
    block-honey-block-place,
    block-honey-block-slide,
    block-honey-block-step,
    item-honeycomb-wax-on,
    item-honey-bottle-drink,
    item-goat-horn-sound-0,
    item-goat-horn-sound-1,
    item-goat-horn-sound-2,
    item-goat-horn-sound-3,
    item-goat-horn-sound-4,
    item-goat-horn-sound-5,
    item-goat-horn-sound-6,
    item-goat-horn-sound-7,
    entity-horse-ambient,
    entity-baby-horse-ambient,
    entity-horse-angry,
    entity-baby-horse-angry,
    entity-horse-armor,
    item-horse-armor-unequip,
    entity-horse-breathe,
    entity-baby-horse-breathe,
    entity-horse-death,
    entity-baby-horse-death,
    entity-horse-eat,
    entity-baby-horse-eat,
    entity-horse-gallop,
    entity-horse-hurt,
    entity-baby-horse-hurt,
    entity-horse-jump,
    entity-horse-land,
    entity-baby-horse-land,
    entity-horse-saddle,
    entity-horse-step,
    entity-baby-horse-step,
    entity-horse-step-wood,
    entity-hostile-big-fall,
    entity-hostile-death,
    entity-hostile-hurt,
    entity-hostile-small-fall,
    entity-hostile-splash,
    entity-hostile-swim,
    entity-husk-ambient,
    entity-husk-converted-to-zombie,
    entity-husk-death,
    entity-husk-hurt,
    entity-husk-step,
    entity-illusioner-ambient,
    entity-illusioner-cast-spell,
    entity-illusioner-death,
    entity-illusioner-hurt,
    entity-illusioner-mirror-move,
    entity-illusioner-prepare-blindness,
    entity-illusioner-prepare-mirror,
    item-ink-sac-use,
    block-iron-break,
    block-iron-step,
    block-iron-place,
    block-iron-hit,
    block-iron-fall,
    block-iron-door-close,
    block-iron-door-open,
    entity-iron-golem-attack,
    entity-iron-golem-damage,
    entity-iron-golem-death,
    entity-iron-golem-hurt,
    entity-iron-golem-repair,
    entity-iron-golem-step,
    block-iron-trapdoor-close,
    block-iron-trapdoor-open,
    entity-item-frame-add-item,
    entity-item-frame-break,
    entity-item-frame-place,
    entity-item-frame-remove-item,
    entity-item-frame-rotate-item,
    entity-item-break,
    entity-item-pickup,
    block-ladder-break,
    block-ladder-fall,
    block-ladder-hit,
    block-ladder-place,
    block-ladder-step,
    block-lantern-break,
    block-lantern-fall,
    block-lantern-hit,
    block-lantern-place,
    block-lantern-step,
    block-large-amethyst-bud-break,
    block-large-amethyst-bud-place,
    block-lava-ambient,
    block-lava-extinguish,
    block-lava-pop,
    block-leaf-litter-break,
    block-leaf-litter-step,
    block-leaf-litter-place,
    block-leaf-litter-hit,
    block-leaf-litter-fall,
    item-lead-untied,
    item-lead-tied,
    item-lead-break,
    block-lever-click,
    entity-lightning-bolt-impact,
    entity-lightning-bolt-thunder,
    entity-lingering-potion-throw,
    entity-llama-ambient,
    entity-llama-angry,
    entity-llama-chest,
    entity-llama-death,
    entity-llama-eat,
    entity-llama-hurt,
    entity-llama-spit,
    entity-llama-step,
    entity-llama-swag,
    item-llama-carpet-unequip,
    entity-magma-cube-death-small,
    block-lodestone-break,
    block-lodestone-step,
    block-lodestone-place,
    block-lodestone-hit,
    block-lodestone-fall,
    item-lodestone-compass-lock,
    item-spear-lunge-1,
    item-spear-lunge-2,
    item-spear-lunge-3,
    item-mace-smash-air,
    item-mace-smash-ground,
    item-mace-smash-ground-heavy,
    entity-magma-cube-death,
    entity-magma-cube-hurt,
    entity-magma-cube-hurt-small,
    entity-magma-cube-jump,
    entity-magma-cube-squish,
    entity-magma-cube-squish-small,
    block-mangrove-roots-break,
    block-mangrove-roots-fall,
    block-mangrove-roots-hit,
    block-mangrove-roots-place,
    block-mangrove-roots-step,
    block-medium-amethyst-bud-break,
    block-medium-amethyst-bud-place,
    block-metal-break,
    block-metal-fall,
    block-metal-hit,
    block-metal-place,
    block-metal-pressure-plate-click-off,
    block-metal-pressure-plate-click-on,
    block-metal-step,
    entity-minecart-inside-underwater,
    entity-minecart-inside,
    entity-minecart-riding,
    entity-mooshroom-convert,
    entity-mooshroom-eat,
    entity-mooshroom-milk,
    entity-mooshroom-suspicious-milk,
    entity-mooshroom-shear,
    block-moss-carpet-break,
    block-moss-carpet-fall,
    block-moss-carpet-hit,
    block-moss-carpet-place,
    block-moss-carpet-step,
    block-pink-petals-break,
    block-pink-petals-fall,
    block-pink-petals-hit,
    block-pink-petals-place,
    block-pink-petals-step,
    block-moss-break,
    block-moss-fall,
    block-moss-hit,
    block-moss-place,
    block-moss-step,
    block-mud-break,
    block-mud-fall,
    block-mud-hit,
    block-mud-place,
    block-mud-step,
    block-mud-bricks-break,
    block-mud-bricks-fall,
    block-mud-bricks-hit,
    block-mud-bricks-place,
    block-mud-bricks-step,
    block-muddy-mangrove-roots-break,
    block-muddy-mangrove-roots-fall,
    block-muddy-mangrove-roots-hit,
    block-muddy-mangrove-roots-place,
    block-muddy-mangrove-roots-step,
    entity-mule-ambient,
    entity-mule-angry,
    entity-mule-chest,
    entity-mule-death,
    entity-mule-eat,
    entity-mule-hurt,
    entity-mule-jump,
    music-creative,
    music-credits,
    music-disc-5,
    music-disc-11,
    music-disc-13,
    music-disc-blocks,
    music-disc-bounce,
    music-disc-cat,
    music-disc-chirp,
    music-disc-far,
    music-disc-lava-chicken,
    music-disc-mall,
    music-disc-mellohi,
    music-disc-pigstep,
    music-disc-stal,
    music-disc-strad,
    music-disc-wait,
    music-disc-ward,
    music-disc-otherside,
    music-disc-relic,
    music-disc-creator,
    music-disc-creator-music-box,
    music-disc-precipice,
    music-disc-tears,
    music-dragon,
    music-end,
    music-game,
    music-menu,
    music-nether-basalt-deltas,
    music-nether-crimson-forest,
    music-overworld-deep-dark,
    music-overworld-dripstone-caves,
    music-overworld-grove,
    music-overworld-jagged-peaks,
    music-overworld-lush-caves,
    music-overworld-swamp,
    music-overworld-forest,
    music-overworld-old-growth-taiga,
    music-overworld-meadow,
    music-overworld-cherry-grove,
    music-nether-nether-wastes,
    music-overworld-frozen-peaks,
    music-overworld-snowy-slopes,
    music-nether-soul-sand-valley,
    music-overworld-stony-peaks,
    music-nether-warped-forest,
    music-overworld-flower-forest,
    music-overworld-desert,
    music-overworld-badlands,
    music-overworld-jungle,
    music-overworld-sparse-jungle,
    music-overworld-bamboo-jungle,
    music-overworld-sulfur-caves,
    music-under-water,
    entity-nautilus-ambient,
    entity-nautilus-ambient-land,
    entity-nautilus-dash,
    entity-nautilus-dash-land,
    entity-nautilus-dash-ready,
    entity-nautilus-dash-ready-land,
    entity-nautilus-death,
    entity-nautilus-death-land,
    entity-nautilus-eat,
    entity-nautilus-hurt,
    entity-nautilus-hurt-land,
    entity-nautilus-swim,
    block-nether-bricks-break,
    block-nether-bricks-step,
    block-nether-bricks-place,
    block-nether-bricks-hit,
    block-nether-bricks-fall,
    block-nether-wart-break,
    item-nether-wart-plant,
    block-nether-wood-break,
    block-nether-wood-fall,
    block-nether-wood-hit,
    block-nether-wood-place,
    block-nether-wood-step,
    block-nether-wood-door-close,
    block-nether-wood-door-open,
    block-nether-wood-trapdoor-close,
    block-nether-wood-trapdoor-open,
    block-nether-wood-button-click-off,
    block-nether-wood-button-click-on,
    block-nether-wood-pressure-plate-click-off,
    block-nether-wood-pressure-plate-click-on,
    block-nether-wood-fence-gate-close,
    block-nether-wood-fence-gate-open,
    intentionally-empty,
    block-packed-mud-break,
    block-packed-mud-fall,
    block-packed-mud-hit,
    block-packed-mud-place,
    block-packed-mud-step,
    block-stem-break,
    block-stem-step,
    block-stem-place,
    block-stem-hit,
    block-stem-fall,
    block-nylium-break,
    block-nylium-step,
    block-nylium-place,
    block-nylium-hit,
    block-nylium-fall,
    block-nether-sprouts-break,
    block-nether-sprouts-step,
    block-nether-sprouts-place,
    block-nether-sprouts-hit,
    block-nether-sprouts-fall,
    block-fungus-break,
    block-fungus-step,
    block-fungus-place,
    block-fungus-hit,
    block-fungus-fall,
    block-weeping-vines-break,
    block-weeping-vines-step,
    block-weeping-vines-place,
    block-weeping-vines-hit,
    block-weeping-vines-fall,
    block-wart-block-break,
    block-wart-block-step,
    block-wart-block-place,
    block-wart-block-hit,
    block-wart-block-fall,
    block-netherite-block-break,
    block-netherite-block-step,
    block-netherite-block-place,
    block-netherite-block-hit,
    block-netherite-block-fall,
    block-netherrack-break,
    block-netherrack-step,
    block-netherrack-place,
    block-netherrack-hit,
    block-netherrack-fall,
    block-note-block-basedrum,
    block-note-block-bass,
    block-note-block-bell,
    block-note-block-chime,
    block-note-block-flute,
    block-note-block-guitar,
    block-note-block-harp,
    block-note-block-hat,
    block-note-block-pling,
    block-note-block-snare,
    block-note-block-trumpet,
    block-note-block-trumpet-exposed,
    block-note-block-trumpet-oxidized,
    block-note-block-trumpet-weathered,
    block-note-block-xylophone,
    block-note-block-iron-xylophone,
    block-note-block-cow-bell,
    block-note-block-didgeridoo,
    block-note-block-bit,
    block-note-block-banjo,
    block-note-block-imitate-zombie,
    block-note-block-imitate-skeleton,
    block-note-block-imitate-creeper,
    block-note-block-imitate-ender-dragon,
    block-note-block-imitate-wither-skeleton,
    block-note-block-imitate-piglin,
    entity-ocelot-hurt,
    entity-ocelot-ambient,
    entity-ocelot-death,
    item-ominous-bottle-dispose,
    entity-painting-break,
    entity-painting-place,
    block-pale-hanging-moss-idle,
    entity-panda-pre-sneeze,
    entity-panda-sneeze,
    entity-panda-ambient,
    entity-panda-death,
    entity-panda-eat,
    entity-panda-step,
    entity-panda-cant-breed,
    entity-panda-aggressive-ambient,
    entity-panda-worried-ambient,
    entity-panda-hurt,
    entity-panda-bite,
    entity-parched-ambient,
    entity-parched-death,
    entity-parched-hurt,
    entity-parched-step,
    entity-parrot-ambient,
    entity-parrot-death,
    entity-parrot-eat,
    entity-parrot-fly,
    entity-parrot-hurt,
    entity-parrot-imitate-blaze,
    entity-parrot-imitate-bogged,
    entity-parrot-imitate-breeze,
    entity-parrot-imitate-camel-husk,
    entity-parrot-imitate-creaking,
    entity-parrot-imitate-creeper,
    entity-parrot-imitate-drowned,
    entity-parrot-imitate-elder-guardian,
    entity-parrot-imitate-ender-dragon,
    entity-parrot-imitate-endermite,
    entity-parrot-imitate-evoker,
    entity-parrot-imitate-ghast,
    entity-parrot-imitate-guardian,
    entity-parrot-imitate-hoglin,
    entity-parrot-imitate-husk,
    entity-parrot-imitate-illusioner,
    entity-parrot-imitate-magma-cube,
    entity-parrot-imitate-phantom,
    entity-parrot-imitate-parched,
    entity-parrot-imitate-piglin,
    entity-parrot-imitate-piglin-brute,
    entity-parrot-imitate-pillager,
    entity-parrot-imitate-ravager,
    entity-parrot-imitate-shulker,
    entity-parrot-imitate-silverfish,
    entity-parrot-imitate-skeleton,
    entity-parrot-imitate-slime,
    entity-parrot-imitate-spider,
    entity-parrot-imitate-stray,
    entity-parrot-imitate-vex,
    entity-parrot-imitate-vindicator,
    entity-parrot-imitate-warden,
    entity-parrot-imitate-witch,
    entity-parrot-imitate-wither,
    entity-parrot-imitate-wither-skeleton,
    entity-parrot-imitate-zoglin,
    entity-parrot-imitate-zombie,
    entity-parrot-imitate-zombie-horse,
    entity-parrot-imitate-zombie-nautilus,
    entity-parrot-imitate-zombie-villager,
    entity-parrot-step,
    entity-phantom-ambient,
    entity-phantom-bite,
    entity-phantom-death,
    entity-phantom-flap,
    entity-phantom-hurt,
    entity-phantom-swoop,
    entity-pig-saddle,
    entity-pig-step,
    entity-baby-pig-step,
    entity-baby-pig-ambient,
    entity-baby-pig-eat,
    entity-baby-pig-hurt,
    entity-baby-pig-death,
    entity-pig-ambient,
    entity-pig-hurt,
    entity-pig-death,
    entity-pig-eat,
    entity-pig-mini-ambient,
    entity-pig-mini-hurt,
    entity-pig-mini-death,
    entity-pig-mini-eat,
    entity-pig-big-ambient,
    entity-pig-big-hurt,
    entity-pig-big-death,
    entity-pig-big-eat,
    entity-piglin-admiring-item,
    entity-piglin-ambient,
    entity-piglin-angry,
    entity-piglin-celebrate,
    entity-piglin-death,
    entity-piglin-jealous,
    entity-piglin-hurt,
    entity-piglin-retreat,
    entity-piglin-step,
    entity-piglin-converted-to-zombified,
    entity-piglin-brute-ambient,
    entity-piglin-brute-angry,
    entity-piglin-brute-death,
    entity-piglin-brute-hurt,
    entity-piglin-brute-step,
    entity-piglin-brute-converted-to-zombified,
    entity-pillager-ambient,
    entity-pillager-celebrate,
    entity-pillager-death,
    entity-pillager-hurt,
    block-piston-contract,
    block-piston-extend,
    entity-player-attack-crit,
    entity-player-attack-knockback,
    entity-player-attack-nodamage,
    entity-player-attack-strong,
    entity-player-attack-sweep,
    entity-player-attack-weak,
    entity-player-big-fall,
    entity-player-breath,
    entity-player-burp,
    entity-player-death,
    entity-player-hurt,
    entity-player-hurt-drown,
    entity-player-hurt-freeze,
    entity-player-hurt-on-fire,
    entity-player-hurt-sweet-berry-bush,
    entity-player-levelup,
    entity-player-small-fall,
    entity-player-splash,
    entity-player-splash-high-speed,
    entity-player-swim,
    entity-player-teleport,
    entity-polar-bear-ambient,
    entity-polar-bear-ambient-baby,
    entity-polar-bear-death,
    entity-polar-bear-hurt,
    entity-polar-bear-step,
    entity-polar-bear-warning,
    block-polished-deepslate-break,
    block-polished-deepslate-fall,
    block-polished-deepslate-hit,
    block-polished-deepslate-place,
    block-polished-deepslate-step,
    block-portal-ambient,
    block-portal-travel,
    block-portal-trigger,
    block-powder-snow-break,
    block-powder-snow-fall,
    block-powder-snow-hit,
    block-powder-snow-place,
    block-powder-snow-step,
    entity-puffer-fish-blow-out,
    entity-puffer-fish-blow-up,
    entity-puffer-fish-death,
    entity-puffer-fish-flop,
    entity-puffer-fish-hurt,
    entity-puffer-fish-sting,
    block-pumpkin-carve,
    entity-rabbit-ambient,
    entity-rabbit-attack,
    entity-rabbit-death,
    entity-rabbit-hurt,
    entity-rabbit-jump,
    event-raid-horn,
    entity-ravager-ambient,
    entity-ravager-attack,
    entity-ravager-celebrate,
    entity-ravager-death,
    entity-ravager-hurt,
    entity-ravager-step,
    entity-ravager-stunned,
    entity-ravager-roar,
    block-nether-gold-ore-break,
    block-nether-gold-ore-fall,
    block-nether-gold-ore-hit,
    block-nether-gold-ore-place,
    block-nether-gold-ore-step,
    block-nether-ore-break,
    block-nether-ore-fall,
    block-nether-ore-hit,
    block-nether-ore-place,
    block-nether-ore-step,
    block-redstone-torch-burnout,
    block-resin-break,
    block-resin-fall,
    block-resin-place,
    block-resin-step,
    block-resin-bricks-break,
    block-resin-bricks-fall,
    block-resin-bricks-hit,
    block-resin-bricks-place,
    block-resin-bricks-step,
    block-respawn-anchor-ambient,
    block-respawn-anchor-charge,
    block-respawn-anchor-deplete,
    block-respawn-anchor-set-spawn,
    block-rooted-dirt-break,
    block-rooted-dirt-fall,
    block-rooted-dirt-hit,
    block-rooted-dirt-place,
    block-rooted-dirt-step,
    entity-salmon-ambient,
    entity-salmon-death,
    entity-salmon-flop,
    entity-salmon-hurt,
    block-sand-break,
    block-sand-fall,
    block-sand-hit,
    block-sand-place,
    block-sand-step,
    block-sand-idle,
    block-scaffolding-break,
    block-scaffolding-fall,
    block-scaffolding-hit,
    block-scaffolding-place,
    block-scaffolding-step,
    block-sculk-spread,
    block-sculk-charge,
    block-sculk-break,
    block-sculk-fall,
    block-sculk-hit,
    block-sculk-place,
    block-sculk-step,
    block-sculk-catalyst-bloom,
    block-sculk-catalyst-break,
    block-sculk-catalyst-fall,
    block-sculk-catalyst-hit,
    block-sculk-catalyst-place,
    block-sculk-catalyst-step,
    block-sculk-sensor-clicking,
    block-sculk-sensor-clicking-stop,
    block-sculk-sensor-break,
    block-sculk-sensor-fall,
    block-sculk-sensor-hit,
    block-sculk-sensor-place,
    block-sculk-sensor-step,
    block-sculk-shrieker-break,
    block-sculk-shrieker-fall,
    block-sculk-shrieker-hit,
    block-sculk-shrieker-place,
    block-sculk-shrieker-shriek,
    block-sculk-shrieker-step,
    block-sculk-vein-break,
    block-sculk-vein-fall,
    block-sculk-vein-hit,
    block-sculk-vein-place,
    block-sculk-vein-step,
    entity-sheep-ambient,
    entity-sheep-death,
    entity-sheep-hurt,
    entity-sheep-shear,
    entity-sheep-step,
    item-shears-snip,
    block-shelf-activate,
    block-shelf-break,
    block-shelf-deactivate,
    block-shelf-fall,
    block-shelf-hit,
    block-shelf-multi-swap,
    block-shelf-place,
    block-shelf-place-item,
    block-shelf-single-swap,
    block-shelf-step,
    block-shelf-take-item,
    item-shield-block,
    item-shield-break,
    block-shroomlight-break,
    block-shroomlight-step,
    block-shroomlight-place,
    block-shroomlight-hit,
    block-shroomlight-fall,
    item-shovel-flatten,
    entity-shulker-ambient,
    block-shulker-box-close,
    block-shulker-box-open,
    entity-shulker-bullet-hit,
    entity-shulker-bullet-hurt,
    entity-shulker-close,
    entity-shulker-death,
    entity-shulker-hurt,
    entity-shulker-hurt-closed,
    entity-shulker-open,
    entity-shulker-shoot,
    entity-shulker-teleport,
    entity-silverfish-ambient,
    entity-silverfish-death,
    entity-silverfish-hurt,
    entity-silverfish-step,
    entity-skeleton-ambient,
    entity-skeleton-converted-to-stray,
    entity-skeleton-death,
    entity-skeleton-horse-ambient,
    entity-skeleton-horse-death,
    entity-skeleton-horse-hurt,
    entity-skeleton-horse-swim,
    entity-skeleton-horse-ambient-water,
    entity-skeleton-horse-gallop-water,
    entity-skeleton-horse-jump-water,
    entity-skeleton-horse-step-water,
    entity-skeleton-hurt,
    entity-skeleton-shoot,
    entity-skeleton-step,
    entity-slime-attack,
    entity-slime-death,
    entity-slime-hurt,
    entity-slime-jump,
    entity-slime-squish,
    block-slime-block-break,
    block-slime-block-fall,
    block-slime-block-hit,
    block-slime-block-place,
    block-slime-block-step,
    block-small-amethyst-bud-break,
    block-small-amethyst-bud-place,
    block-small-dripleaf-break,
    block-small-dripleaf-fall,
    block-small-dripleaf-hit,
    block-small-dripleaf-place,
    block-small-dripleaf-step,
    block-soul-sand-break,
    block-soul-sand-step,
    block-soul-sand-place,
    block-soul-sand-hit,
    block-soul-sand-fall,
    block-soul-soil-break,
    block-soul-soil-step,
    block-soul-soil-place,
    block-soul-soil-hit,
    block-soul-soil-fall,
    particle-soul-escape,
    block-spawner-break,
    block-spawner-fall,
    block-spawner-hit,
    block-spawner-place,
    block-spawner-step,
    item-spear-use,
    item-spear-hit,
    item-spear-attack,
    item-spear-wood-use,
    item-spear-wood-hit,
    item-spear-wood-attack,
    block-spore-blossom-break,
    block-spore-blossom-fall,
    block-spore-blossom-hit,
    block-spore-blossom-place,
    block-spore-blossom-step,
    entity-strider-ambient,
    entity-strider-happy,
    entity-strider-retreat,
    entity-strider-death,
    entity-strider-hurt,
    entity-strider-step,
    entity-strider-step-lava,
    entity-strider-eat,
    entity-strider-saddle,
    entity-slime-death-small,
    entity-slime-hurt-small,
    entity-slime-jump-small,
    entity-slime-squish-small,
    block-smithing-table-use,
    block-smoker-smoke,
    entity-sniffer-step,
    entity-sniffer-eat,
    entity-sniffer-idle,
    entity-sniffer-hurt,
    entity-sniffer-death,
    entity-sniffer-drop-seed,
    entity-sniffer-scenting,
    entity-sniffer-sniffing,
    entity-sniffer-searching,
    entity-sniffer-digging,
    entity-sniffer-digging-stop,
    entity-sniffer-happy,
    block-sniffer-egg-plop,
    block-sniffer-egg-crack,
    block-sniffer-egg-hatch,
    entity-snowball-throw,
    block-snow-break,
    block-snow-fall,
    entity-snow-golem-ambient,
    entity-snow-golem-death,
    entity-snow-golem-hurt,
    entity-snow-golem-shoot,
    entity-snow-golem-shear,
    block-snow-hit,
    block-snow-place,
    block-snow-step,
    entity-spider-ambient,
    entity-spider-death,
    entity-spider-hurt,
    entity-spider-step,
    entity-splash-potion-break,
    entity-splash-potion-throw,
    block-sponge-break,
    block-sponge-fall,
    block-sponge-hit,
    block-sponge-place,
    block-sponge-step,
    block-sponge-absorb,
    item-spyglass-use,
    item-spyglass-stop-using,
    entity-squid-ambient,
    entity-squid-death,
    entity-squid-hurt,
    entity-squid-squirt,
    block-stone-break,
    block-stone-button-click-off,
    block-stone-button-click-on,
    block-stone-fall,
    block-stone-hit,
    block-stone-place,
    block-stone-pressure-plate-click-off,
    block-stone-pressure-plate-click-on,
    block-stone-step,
    entity-stray-ambient,
    entity-stray-death,
    entity-stray-hurt,
    entity-stray-step,
    block-sulfur-spike-break,
    block-sulfur-spike-step,
    block-sulfur-spike-place,
    block-sulfur-spike-hit,
    block-sulfur-spike-fall,
    block-sulfur-spike-land,
    block-sweet-berry-bush-break,
    block-sweet-berry-bush-place,
    block-sweet-berry-bush-pick-berries,
    entity-tadpole-death,
    entity-tadpole-flop,
    entity-tadpole-grow-up,
    entity-tadpole-hurt,
    enchant-thorns-hit,
    entity-tnt-primed,
    item-totem-use,
    item-trident-hit,
    item-trident-hit-ground,
    item-trident-return,
    item-trident-riptide-1,
    item-trident-riptide-2,
    item-trident-riptide-3,
    item-trident-throw,
    item-trident-thunder,
    block-tripwire-attach,
    block-tripwire-click-off,
    block-tripwire-click-on,
    block-tripwire-detach,
    entity-tropical-fish-ambient,
    entity-tropical-fish-death,
    entity-tropical-fish-flop,
    entity-tropical-fish-hurt,
    block-tuff-break,
    block-tuff-step,
    block-tuff-place,
    block-tuff-hit,
    block-tuff-fall,
    block-tuff-bricks-break,
    block-tuff-bricks-fall,
    block-tuff-bricks-hit,
    block-tuff-bricks-place,
    block-tuff-bricks-step,
    block-polished-tuff-break,
    block-polished-tuff-fall,
    block-polished-tuff-hit,
    block-polished-tuff-place,
    block-polished-tuff-step,
    entity-turtle-ambient-land,
    entity-turtle-death,
    entity-turtle-death-baby,
    entity-turtle-egg-break,
    entity-turtle-egg-crack,
    entity-turtle-egg-hatch,
    entity-turtle-hurt,
    entity-turtle-hurt-baby,
    entity-turtle-lay-egg,
    entity-turtle-shamble,
    entity-turtle-shamble-baby,
    entity-turtle-swim,
    ui-button-click,
    ui-loom-select-pattern,
    ui-loom-take-result,
    ui-cartography-table-take-result,
    ui-stonecutter-take-result,
    ui-stonecutter-select-recipe,
    ui-toast-challenge-complete,
    ui-toast-in,
    ui-toast-out,
    block-vault-activate,
    block-vault-ambient,
    block-vault-break,
    block-vault-close-shutter,
    block-vault-deactivate,
    block-vault-eject-item,
    block-vault-reject-rewarded-player,
    block-vault-fall,
    block-vault-hit,
    block-vault-insert-item,
    block-vault-insert-item-fail,
    block-vault-open-shutter,
    block-vault-place,
    block-vault-step,
    entity-vex-ambient,
    entity-vex-charge,
    entity-vex-death,
    entity-vex-hurt,
    entity-villager-ambient,
    entity-villager-celebrate,
    entity-villager-death,
    entity-villager-hurt,
    entity-villager-no,
    entity-villager-trade,
    entity-villager-yes,
    entity-villager-work-armorer,
    entity-villager-work-butcher,
    entity-villager-work-cartographer,
    entity-villager-work-cleric,
    entity-villager-work-farmer,
    entity-villager-work-fisherman,
    entity-villager-work-fletcher,
    entity-villager-work-leatherworker,
    entity-villager-work-librarian,
    entity-villager-work-mason,
    entity-villager-work-shepherd,
    entity-villager-work-toolsmith,
    entity-villager-work-weaponsmith,
    entity-vindicator-ambient,
    entity-vindicator-celebrate,
    entity-vindicator-death,
    entity-vindicator-hurt,
    block-vine-break,
    block-vine-fall,
    block-vine-hit,
    block-vine-place,
    block-vine-step,
    block-lily-pad-place,
    entity-wandering-trader-ambient,
    entity-wandering-trader-death,
    entity-wandering-trader-disappeared,
    entity-wandering-trader-drink-milk,
    entity-wandering-trader-drink-potion,
    entity-wandering-trader-hurt,
    entity-wandering-trader-no,
    entity-wandering-trader-reappeared,
    entity-wandering-trader-trade,
    entity-wandering-trader-yes,
    entity-warden-agitated,
    entity-warden-ambient,
    entity-warden-angry,
    entity-warden-attack-impact,
    entity-warden-death,
    entity-warden-dig,
    entity-warden-emerge,
    entity-warden-heartbeat,
    entity-warden-hurt,
    entity-warden-listening,
    entity-warden-listening-angry,
    entity-warden-nearby-close,
    entity-warden-nearby-closer,
    entity-warden-nearby-closest,
    entity-warden-roar,
    entity-warden-sniff,
    entity-warden-sonic-boom,
    entity-warden-sonic-charge,
    entity-warden-step,
    entity-warden-tendril-clicks,
    block-hanging-sign-waxed-interact-fail,
    block-sign-waxed-interact-fail,
    block-water-ambient,
    weather-end-flash,
    weather-rain,
    weather-rain-above,
    block-wet-grass-break,
    block-wet-grass-fall,
    block-wet-grass-hit,
    block-wet-grass-place,
    block-wet-grass-step,
    block-wet-sponge-break,
    block-wet-sponge-dries,
    block-wet-sponge-fall,
    block-wet-sponge-hit,
    block-wet-sponge-place,
    block-wet-sponge-step,
    entity-wind-charge-wind-burst,
    entity-wind-charge-throw,
    entity-witch-ambient,
    entity-witch-celebrate,
    entity-witch-death,
    entity-witch-drink,
    entity-witch-hurt,
    entity-witch-throw,
    entity-wither-ambient,
    entity-wither-break-block,
    entity-wither-death,
    entity-wither-hurt,
    entity-wither-shoot,
    entity-wither-skeleton-ambient,
    entity-wither-skeleton-death,
    entity-wither-skeleton-hurt,
    entity-wither-skeleton-step,
    entity-wither-spawn,
    item-wolf-armor-break,
    entity-baby-wolf-ambient,
    item-wolf-armor-crack,
    item-wolf-armor-damage,
    item-wolf-armor-repair,
    entity-baby-wolf-death,
    entity-baby-wolf-growl,
    entity-baby-wolf-hurt,
    entity-baby-wolf-pant,
    entity-wolf-shake,
    entity-wolf-step,
    entity-baby-wolf-step,
    entity-baby-wolf-whine,
    entity-wolf-ambient,
    entity-wolf-death,
    entity-wolf-growl,
    entity-wolf-hurt,
    entity-wolf-pant,
    entity-wolf-whine,
    entity-wolf-puglin-ambient,
    entity-wolf-puglin-death,
    entity-wolf-puglin-growl,
    entity-wolf-puglin-hurt,
    entity-wolf-puglin-pant,
    entity-wolf-puglin-whine,
    entity-wolf-sad-ambient,
    entity-wolf-sad-death,
    entity-wolf-sad-growl,
    entity-wolf-sad-hurt,
    entity-wolf-sad-pant,
    entity-wolf-sad-whine,
    entity-wolf-angry-ambient,
    entity-wolf-angry-death,
    entity-wolf-angry-growl,
    entity-wolf-angry-hurt,
    entity-wolf-angry-pant,
    entity-wolf-angry-whine,
    entity-wolf-grumpy-ambient,
    entity-wolf-grumpy-death,
    entity-wolf-grumpy-growl,
    entity-wolf-grumpy-hurt,
    entity-wolf-grumpy-pant,
    entity-wolf-grumpy-whine,
    entity-wolf-big-ambient,
    entity-wolf-big-death,
    entity-wolf-big-growl,
    entity-wolf-big-hurt,
    entity-wolf-big-pant,
    entity-wolf-big-whine,
    entity-wolf-cute-ambient,
    entity-wolf-cute-death,
    entity-wolf-cute-growl,
    entity-wolf-cute-hurt,
    entity-wolf-cute-pant,
    entity-wolf-cute-whine,
    block-wooden-door-close,
    block-wooden-door-open,
    block-wooden-trapdoor-close,
    block-wooden-trapdoor-open,
    block-wooden-button-click-off,
    block-wooden-button-click-on,
    block-wooden-pressure-plate-click-off,
    block-wooden-pressure-plate-click-on,
    block-wood-break,
    block-wood-fall,
    block-wood-hit,
    block-wood-place,
    block-wood-step,
    block-wool-break,
    block-wool-fall,
    block-wool-hit,
    block-wool-place,
    block-wool-step,
    entity-zoglin-ambient,
    entity-zoglin-angry,
    entity-zoglin-attack,
    entity-zoglin-death,
    entity-zoglin-hurt,
    entity-zoglin-step,
    entity-zombie-ambient,
    entity-zombie-attack-wooden-door,
    entity-zombie-attack-iron-door,
    entity-zombie-break-wooden-door,
    entity-zombie-converted-to-drowned,
    entity-zombie-death,
    entity-zombie-destroy-egg,
    entity-zombie-horse-ambient,
    entity-zombie-horse-angry,
    entity-zombie-horse-death,
    entity-zombie-horse-eat,
    entity-zombie-horse-hurt,
    entity-zombie-hurt,
    entity-zombie-infect,
    entity-zombie-nautilus-ambient,
    entity-zombie-nautilus-ambient-land,
    entity-zombie-nautilus-dash,
    entity-zombie-nautilus-dash-land,
    entity-zombie-nautilus-dash-ready,
    entity-zombie-nautilus-dash-ready-land,
    entity-zombie-nautilus-death,
    entity-zombie-nautilus-death-land,
    entity-zombie-nautilus-eat,
    entity-zombie-nautilus-hurt,
    entity-zombie-nautilus-hurt-land,
    entity-zombie-nautilus-swim,
    entity-zombified-piglin-ambient,
    entity-zombified-piglin-angry,
    entity-zombified-piglin-death,
    entity-zombified-piglin-hurt,
    entity-zombie-step,
    entity-zombie-villager-ambient,
    entity-zombie-villager-converted,
    entity-zombie-villager-cure,
    entity-zombie-villager-death,
    entity-zombie-villager-hurt,
    entity-zombie-villager-step,
    event-mob-effect-bad-omen,
    event-mob-effect-trial-omen,
    event-mob-effect-raid-omen,
    item-saddle-unequip,
    item-nautilus-saddle-underwater-equip,
    item-nautilus-saddle-equip,
    block-sulfur-break,
    block-sulfur-step,
    block-sulfur-place,
    block-sulfur-hit,
    block-sulfur-fall,
    block-potent-sulfur-break,
    block-potent-sulfur-step,
    block-potent-sulfur-place,
    block-potent-sulfur-hit,
    block-potent-sulfur-fall,
    block-potent-sulfur-geyser-eruption,
    block-potent-sulfur-geyser-eruption-active,
    block-potent-sulfur-geyser-continuous-eruption,
    block-potent-sulfur-geyser-continuous-eruption-active,
    block-cinnabar-break,
    block-cinnabar-step,
    block-cinnabar-place,
    block-cinnabar-hit,
    block-cinnabar-fall,
    entity-sulfur-cube-absorb,
    entity-sulfur-cube-bounce,
    entity-sulfur-cube-death,
    entity-sulfur-cube-eject,
    entity-sulfur-cube-hurt,
    entity-sulfur-cube-jump,
    entity-sulfur-cube-regular-hit,
    entity-sulfur-cube-regular-push,
    entity-sulfur-cube-bouncy-hit,
    entity-sulfur-cube-bouncy-push,
    entity-sulfur-cube-slow-bouncy-hit,
    entity-sulfur-cube-slow-bouncy-push,
    entity-sulfur-cube-slow-flat-hit,
    entity-sulfur-cube-slow-flat-push,
    entity-sulfur-cube-fast-flat-hit,
    entity-sulfur-cube-fast-flat-push,
    entity-sulfur-cube-light-hit,
    entity-sulfur-cube-light-push,
    entity-sulfur-cube-fast-sliding-hit,
    entity-sulfur-cube-fast-sliding-push,
    entity-sulfur-cube-slow-sliding-hit,
    entity-sulfur-cube-slow-sliding-push,
    entity-sulfur-cube-sticky-hit,
    entity-sulfur-cube-sticky-push,
    entity-sulfur-cube-high-resistance-hit,
    entity-sulfur-cube-high-resistance-push,
    entity-sulfur-cube-explosive-hit,
    entity-sulfur-cube-explosive-push,
    entity-sulfur-cube-hot-hit,
    entity-sulfur-cube-hot-push,
    entity-sulfur-cube-squish,
    block-potent-sulfur-noxious-gas,
    entity-small-sulfur-cube-death,
    entity-small-sulfur-cube-hurt,
    entity-small-sulfur-cube-jump,
    entity-small-sulfur-cube-squish,
    entity-small-sulfur-cube-eat,
  }
}
