package pumpkin:plugin@0.1.0;

interface status-effect {
    enum status-effect-type {
        speed,
        slowness,
        haste,
        mining-fatigue,
        strength,
        instant-health,
        instant-damage,
        jump-boost,
        nausea,
        regeneration,
        resistance,
        fire-resistance,
        water-breathing,
        invisibility,
        blindness,
        night-vision,
        hunger,
        weakness,
        poison,
        wither,
        health-boost,
        absorption,
        saturation,
        glowing,
        levitation,
        luck,
        unluck,
        slow-falling,
        conduit-power,
        dolphins-grace,
        bad-omen,
        hero-of-the-village,
        darkness,
        trial-omen,
        raid-omen,
        wind-charged,
        weaving,
        oozing,
        infested,
    }

    record status-effect-instance {
        effect-type: status-effect-type,
        duration: u32,
        amplifier: u8,
        ambient: bool,
        show-particles: bool,
        show-icon: bool,
    }
}
