package pumpkin:plugin@0.1.0;

interface statistics {
  enum statistic-category {
    mined,
    crafted,
    used,
    broken,
    picked-up,
    dropped,
    killed,
    killed-by,
    custom,
  }
  enum custom-statistic {
    leave-game,
    play-time,
    total-world-time,
    time-since-death,
    time-since-rest,
    sneak-time,
    walk-one-cm,
    crouch-one-cm,
    sprint-one-cm,
    walk-on-water-one-cm,
    fall-one-cm,
    climb-one-cm,
    fly-one-cm,
    walk-under-water-one-cm,
    minecart-one-cm,
    boat-one-cm,
    pig-one-cm,
    happy-ghast-one-cm,
    horse-one-cm,
    aviate-one-cm,
    swim-one-cm,
    strider-one-cm,
    nautilus-one-cm,
    jump,
    drop,
    damage-dealt,
    damage-dealt-absorbed,
    damage-dealt-resisted,
    damage-taken,
    damage-blocked-by-shield,
    damage-absorbed,
    damage-resisted,
    deaths,
    mob-kills,
    animals-bred,
    player-kills,
    fish-caught,
    talked-to-villager,
    traded-with-villager,
    eat-cake-slice,
    fill-cauldron,
    use-cauldron,
    clean-armor,
    clean-banner,
    clean-shulker-box,
    interact-with-brewingstand,
    interact-with-beacon,
    inspect-dropper,
    inspect-hopper,
    inspect-dispenser,
    play-noteblock,
    tune-noteblock,
    pot-flower,
    trigger-trapped-chest,
    open-enderchest,
    enchant-item,
    play-record,
    interact-with-furnace,
    interact-with-crafting-table,
    open-chest,
    sleep-in-bed,
    open-shulker-box,
    open-barrel,
    interact-with-blast-furnace,
    interact-with-smoker,
    interact-with-lectern,
    interact-with-campfire,
    interact-with-cartography-table,
    interact-with-loom,
    interact-with-stonecutter,
    bell-ring,
    raid-trigger,
    raid-win,
    interact-with-anvil,
    interact-with-grindstone,
    target-hit,
    interact-with-smithing-table,
  }
}
